services:
  - name: connectedu-api 
    type: web
    repo: https://github.com/Natethebuilder/ConnectEdu
    runtime: node
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    region: frankfurt
    autoDeployTrigger: commit
    envVars:
      MONGO_URI: ""
      SUPABASE_URL: ""
      SUPABASE_SERVICE_ROLE_KEY: ""
      JWT_SECRET: ""
      CORS_ORIGIN: ""
      PORT: ""
