services:
  - type: web
    name: connectedu-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      MONGO_URI: ""
      SUPABASE_URL: ""
      SUPABASE_SERVICE_ROLE_KEY: ""
      JWT_SECRET: ""
      CORS_ORIGIN: ""
      PORT: ""
